// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingCart.Context;

#nullable disable

namespace ShoppingCart.Migrations
{
    [DbContext(typeof(dbconnection))]
    [Migration("20240517180545_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingCart.Model.orders", b =>
                {
                    b.Property<Guid>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("pizzaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("orderId");

                    b.HasIndex("pizzaId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("ShoppingCart.Model.pizzas", b =>
                {
                    b.Property<Guid>("pizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("pizzaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pizzaPrice")
                        .HasColumnType("int");

                    b.HasKey("pizzaId");

                    b.ToTable("pizzas");
                });

            modelBuilder.Entity("ShoppingCart.Model.orders", b =>
                {
                    b.HasOne("ShoppingCart.Model.pizzas", "pizza")
                        .WithMany()
                        .HasForeignKey("pizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pizza");
                });
#pragma warning restore 612, 618
        }
    }
}
