name = input("Enter your name: ")
age = input("Enter your age: ")
dob = input("Enter your date of birth (DD/MM/YYYY): ")
phone = input("Enter your phone number: ")
print("Name:", name)
print("Age:", age)
print("Date of Birth:", dob)
print("Phone Number:", phone)